### ISSUE TITLE
Sn 11471 《Fate/stay night [Heaven's Feel] I. 預示之花[電影]》下載問題

### ISSUE THREAD

**Issue by imball** [miyouzi/aniGamerPlus#10]
如題，這部動畫我已經嘗試下載好幾次，不管是獨立出來下載，還是使用命令行都會出問題(無法下載)
上字(cmd):
D:\aniGamerPlus_v11_windows_64bit>python aniGamerPlus.py -s 11471 -c
當前aniGamerPlus版本: v11.01
使用命令行模式, 指定下載到當前目錄:
    D:\aniGamerPlus_v11_windows_64bit
未设定下载解析度, 将使用配置文件指定的清晰度: 1080P
當前下載模式: 僅下載本集

正在下載: sn=11471 Fate/stay night [Heaven's Feel] I. 預示之花[電影].mp4 100.0%
2019-04-14 03:10:26 下載狀態: sn=11471 Fate/stay night [Heaven's Feel] I. 預示之花[電影].mp4 下載完成, 正在解密合并……
2019-04-14 03:15:52 下載狀態: sn=11471 Fate/stay night [Heaven's Feel] I. 預示之花[電影].mp4 解密合并完成, 正在移至番劇 目錄……
Traceback (most recent call last):
  File "C:\Users\a5230\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'D:\\aniGamerPlus_v11_windows_64bit\\temp\\Fatestay night [Heavens Feel] I. 預示之花[電影].MERGING.mp4' -> 'D:\\aniGamerPlus_v11_windows_64bit\\Fatestay night \\Fatestay night [Heavens Feel] I. 預示之花[電影].mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 658, in <module>
    __cui(arg.sn, resolution, download_mode, thread_limit, download_episodes, save_dir, classify, get_info=arg.information_only)
  File "aniGamerPlus.py", line 391, in __cui
    anime.download(cui_resolution, cui_save_dir, realtime_show_file_size=True, classify=classify)
  File "D:\aniGamerPlus_v11_windows_64bit\Anime.py", line 647, in download
    self.__segment_download_mode(resolution)
  File "D:\aniGamerPlus_v11_windows_64bit\Anime.py", line 462, in __segment_download_mode
    shutil.move(merging_file, output_file)
  File "C:\Users\a5230\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "C:\Users\a5230\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\a5230\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\aniGamerPlus_v11_windows_64bit\\Fatestay night \\Fatestay night [Heavens Feel] I. 預示之花[電影].mp4'
附圖:
![1555183440439](https://user-images.githubusercontent.com/49181460/56084371-c49ee900-5e64-11e9-9441-855c72299c0d.jpg)

附上log(第1216列起):
[2019-04-14.log](https://github.com/miyouzi/aniGamerPlus/files/3076651/2019-04-14.log)

**Comment by a0960211197** [comment]
<img width="960" alt="螢幕快照 2019-04-14 08 40 44" src="https://user-images.githubusercontent.com/47473831/56086870-34779880-5e92-11e9-8635-2bbeefe40d19.png">

這個問題似乎是Windows特有的路徑問題
影片檔名有斜線的字元，被Windows識別為路徑分層符號。
檔名不允許有斜線跟反斜線的字元。
所以合併之後要移到目錄時就會找不到檔名！

我用Mac OS Ｘ沒有這個問題

<img width="1181" alt="螢幕快照 2019-04-14 08 05 52" src="https://user-images.githubusercontent.com/47473831/56086873-4d804980-5e92-11e9-89ea-b0f50e1f71de.png">

不過檔案還是有轉換完成會在Temp的資料夾內，可以先拉出來。

**Comment by miyouzi** [comment]
是的，檔案名帶有```/``` 在Windows會有這個問題，可以加一個判斷如果在 Windows 下將```/```替換成替他字元，空格可以嗎？或者有其他推薦？

**Comment by a0960211197** [comment]
把它改成全型的／這樣就可以避開了。

**Comment by miyouzi** [comment]
@a0960211197 OK，稍後更新，另外```/```在 Mac OS Ｘ裏不會識別成資料夾麽？

**Comment by a0960211197** [comment]
我剛試了一下
Mac OS X 會自動把 “/” 替換成 ”:“ 
也可以建立有"/"跟"\"的資料夾
在路徑上系統會自動轉換
<img width="383" alt="螢幕快照 2019-04-14 10 17 21" src="https://user-images.githubusercontent.com/47473831/56087473-c4234400-5e9e-11e9-93d2-f23125c2fcc5.png">

希望這個資訊能幫助到你～

**Comment by miyouzi** [comment]
@a0960211197 感謝你的測試，這應該算 OS X 特別的地方，不適用其他Linux。
把非法字元全部替換成全型或中文應該會比較好

**Comment by miyouzi** [comment]
[v11.1](https://github.com/miyouzi/aniGamerPlus/releases/tag/v11.1) 已更新

**Comment by imball** [comment]
經過測試沒有問題，感謝!
![1555226715490](https://user-images.githubusercontent.com/49181460/56089705-9c95a100-5ec9-11e9-9650-e5c0d2dce01d.jpg)
