### ISSUE TITLE
VIP到期後不能下載限制級

### ISSUE THREAD

**Issue by 0212908** [miyouzi/aniGamerPlus#107]
## 問題描述
原本還在vip可以下載限制級的 到期之後不能下載限制級
限制級確定用網頁版可以觀看 其他正常影片的下載也正常

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

2021-06-29 00:39:57 收到錯誤: sn=11058	《新妹魔王的契約者 [10]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
2021-06-29 00:39:57 收到錯誤: sn=11057	《新妹魔王的契約者 [9]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
2021-06-29 00:39:57 下載異常: sn=11058	發生未知錯誤: 1
2021-06-29 00:39:57 下載異常: sn=11058	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 801, in download
  File "Anime.py", line 449, in __get_m3u8_dict
SystemExit: 1

2021-06-29 00:39:57 解析模式: sn=11059	Web解析
2021-06-29 00:39:57 下載異常: sn=11057	發生未知錯誤: 1
2021-06-29 00:39:57 下載異常: sn=11057	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 801, in download
  File "Anime.py", line 449, in __get_m3u8_dict
SystemExit: 1

2021-06-29 00:39:57 解析模式: sn=11060	Web解析
2021-06-29 00:39:57 任务失敗: sn=11058	title="新妹魔王的契約者 [10]" 從任務列隊中移除, 等待下次更新重試.
2021-06-29 00:39:57 任务失敗: sn=11057	title="新妹魔王的契約者 [9]" 從任務列隊中移除, 等待下次更新重試.
2021-06-29 00:39:58 收到錯誤: sn=11059	《新妹魔王的契約者 [11]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
2021-06-29 00:39:58 下載異常: sn=11059	發生未知錯誤: 1
2021-06-29 00:39:58 下載異常: sn=11059	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 801, in download
  File "Anime.py", line 449, in __get_m3u8_dict
SystemExit: 1

2021-06-29 00:39:58 解析模式: sn=6130	Web解析
2021-06-29 00:39:58 任务失敗: sn=11059	title="新妹魔王的契約者 [11]" 從任務列隊中移除, 等待下次更新重試.
2021-06-29 00:39:58 收到錯誤: sn=11060	《新妹魔王的契約者 [12]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
2021-06-29 00:39:58 下載異常: sn=11060	發生未知錯誤: 1
2021-06-29 00:39:58 下載異常: sn=11060	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 801, in download
  File "Anime.py", line 449, in __get_m3u8_dict
SystemExit: 1

2021-06-29 00:39:58 解析模式: sn=6131	Web解析
2021-06-29 00:39:58 任务失敗: sn=11060	title="新妹魔王的契約者 [12]" 從任務列隊中移除, 等待下次更新重試.
2021-06-29 00:39:58 正在等待: sn=6130	《文豪野犬 [1]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-06-29 00:39:58 正在等待: sn=6131	《文豪野犬 [2]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-06-29 00:40:24 正在下載: sn=6131	文豪野犬[2][720P] 線上看 - 巴哈姆特動畫瘋.mp4 title=文豪野犬 [2]
2021-06-29 00:40:24 正在下載: sn=6130	文豪野犬[1][720P] 線上看 - 巴哈姆特動畫瘋.mp4 title=文豪野犬 [1]

**Comment by 0212908** [comment]
> ## 問題描述
> 原本還在vip可以下載限制級的 到期之後不能下載限制級
> 限制級確定用網頁版可以觀看 其他正常影片的下載也正常
> 
> ## 錯誤截圖
> #在這裏附上錯誤的窗口截圖#
> 
> ## config.json 配置
> ```
> #將你的config.json内容複製到這裏#
> ```
> 
> ## sn_list.txt 配置
> ```
> #將你的sn_list.txt内容複製到這裏#
> ```
> 
> **最好上傳 log 檔案**
> 
> 2021-06-29 00:39:57 收到錯誤: sn=11058 《新妹魔王的契約者 [10]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
> 2021-06-29 00:39:57 收到錯誤: sn=11057 《新妹魔王的契約者 [9]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
> 2021-06-29 00:39:57 下載異常: sn=11058 發生未知錯誤: 1
> 2021-06-29 00:39:57 下載異常: sn=11058 異常詳情:
> Traceback (most recent call last):
> File "aniGamerPlus.py", line 228, in worker
> File "Anime.py", line 801, in download
> File "Anime.py", line 449, in __get_m3u8_dict
> SystemExit: 1
> 
> 2021-06-29 00:39:57 解析模式: sn=11059 Web解析
> 2021-06-29 00:39:57 下載異常: sn=11057 發生未知錯誤: 1
> 2021-06-29 00:39:57 下載異常: sn=11057 異常詳情:
> Traceback (most recent call last):
> File "aniGamerPlus.py", line 228, in worker
> File "Anime.py", line 801, in download
> File "Anime.py", line 449, in __get_m3u8_dict
> SystemExit: 1
> 
> 2021-06-29 00:39:57 解析模式: sn=11060 Web解析
> 2021-06-29 00:39:57 任务失敗: sn=11058 title="新妹魔王的契約者 [10]" 從任務列隊中移除, 等待下次更新重試.
> 2021-06-29 00:39:57 任务失敗: sn=11057 title="新妹魔王的契約者 [9]" 從任務列隊中移除, 等待下次更新重試.
> 2021-06-29 00:39:58 收到錯誤: sn=11059 《新妹魔王的契約者 [11]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
> 2021-06-29 00:39:58 下載異常: sn=11059 發生未知錯誤: 1
> 2021-06-29 00:39:58 下載異常: sn=11059 異常詳情:
> Traceback (most recent call last):
> File "aniGamerPlus.py", line 228, in worker
> File "Anime.py", line 801, in download
> File "Anime.py", line 449, in __get_m3u8_dict
> SystemExit: 1
> 
> 2021-06-29 00:39:58 解析模式: sn=6130 Web解析
> 2021-06-29 00:39:58 任务失敗: sn=11059 title="新妹魔王的契約者 [11]" 從任務列隊中移除, 等待下次更新重試.
> 2021-06-29 00:39:58 收到錯誤: sn=11060 《新妹魔王的契約者 [12]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
> 2021-06-29 00:39:58 下載異常: sn=11060 發生未知錯誤: 1
> 2021-06-29 00:39:58 下載異常: sn=11060 異常詳情:
> Traceback (most recent call last):
> File "aniGamerPlus.py", line 228, in worker
> File "Anime.py", line 801, in download
> File "Anime.py", line 449, in __get_m3u8_dict
> SystemExit: 1
> 
> 2021-06-29 00:39:58 解析模式: sn=6131 Web解析
> 2021-06-29 00:39:58 任务失敗: sn=11060 title="新妹魔王的契約者 [12]" 從任務列隊中移除, 等待下次更新重試.
> 2021-06-29 00:39:58 正在等待: sn=6130 《文豪野犬 [1]》 由於不是VIP賬戶, 正在等待25s廣告時間
> 2021-06-29 00:39:58 正在等待: sn=6131 《文豪野犬 [2]》 由於不是VIP賬戶, 正在等待25s廣告時間
> 2021-06-29 00:40:24 正在下載: sn=6131 文豪野犬[2][720P] 線上看 - 巴哈姆特動畫瘋.mp4 title=文豪野犬 [2]
> 2021-06-29 00:40:24 正在下載: sn=6130 文豪野犬[1][720P] 線上看 - 巴哈姆特動畫瘋.mp4 title=文豪野犬 [1]

另外問一下 有辦法址下載彈幕不下載影片嗎 
因為這片快下架了 我有別的方法可以下載影片 
但沒法下載彈幕

**Comment by fmnijk** [comment]
不用vip也可以載，你這只是cookie過期了，重抓一次cookie試試

**Comment by 0212908** [comment]
我試過 是用無痕模式抓

**Comment by miyouzi** [comment]
@0212908 log發一下，然後程式所在資料夾也截圖一下，我看下有哪些文件

**Comment by 0212908** [comment]
謝謝 我回家的時候用

**Comment by miyouzi** [comment]
https://github.com/miyouzi/aniGamerPlus/releases/tag/v22.1  嘗試新版本看看

**Comment by 0212908** [comment]
> https://github.com/miyouzi/aniGamerPlus/releases/tag/v22.1 嘗試新版本看看

謝謝 但新版本 我win7 64位元 連開都不能開 會跳錯誤
22.1版本容量比較小是嗎

之前我再找有什麼是限制級 因為新妹魔王已經到期了 
後來有發現 從零開始的異世界生活 第15集是18禁 
雖然看過了 但可以用來測試

2021-07-20 18:24:53 檢查更新 檢查更新成功
2021-07-20 18:24:53 發現GitHub上有新版本: v22.1
更新内容:
**修復**

 - 修復集數提取問題 #109

 - 修復Cookie刷新 #110 #107

 - 自動轉換Cookie内中文内容 #100 #106
 
2021-07-20 18:24:54 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v22.0 
2021-07-20 18:24:54 工作目錄: E:\Downloads\aniGamerPlus_v22.0_windows_64bit 
2021-07-20 18:24:55 刪除過期日志: 2021-05-18.log 
2021-07-20 18:25:06 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2021-07-20 18:25:06 開始更新 
2021-07-20 18:25:06 讀取cookie 未發現cookie檔案
2021-07-20 18:25:06 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-07-20 18:25:06 更新终了 
2021-07-20 18:28:27 Dashboard 通過 Web 控制臺更新了 sn_list
2021-07-20 18:28:35 檢查更新 檢查更新成功
2021-07-20 18:28:35 發現GitHub上有新版本: v22.1
更新内容:
**修復**

 - 修復集數提取問題 #109

 - 修復Cookie刷新 #110 #107

 - 自動轉換Cookie内中文内容 #100 #106
 
2021-07-20 18:28:35 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v22.0 
2021-07-20 18:28:35 工作目錄: E:\Downloads\aniGamerPlus_v22.0_windows_64bit 
2021-07-20 18:28:37 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2021-07-20 18:28:37 開始更新 
2021-07-20 18:28:37 讀取cookie 未發現cookie檔案
2021-07-20 18:28:37 解析模式: sn=5791	Web解析
2021-07-20 18:28:38 更新資訊: sn=5791	正在檢查《Re：從零開始的異世界生活》
2021-07-20 18:28:38 加入任务列隊: sn=5791	
2021-07-20 18:28:38 更新資訊 本次更新添加了 1 個新任務, 目前列隊中共有 1 個任務
2021-07-20 18:28:38 更新终了 
2021-07-20 18:28:38 解析模式: sn=5791	Web解析
2021-07-20 18:28:38 收到錯誤: sn=5791	《Re：從零開始的異世界生活 [15]》 code=1016 message: 本作為限制級，須登入您的巴哈帳號！
2021-07-20 18:28:38 下載異常: sn=5791	發生未知錯誤: 1
2021-07-20 18:28:38 下載異常: sn=5791	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 801, in download
  File "Anime.py", line 449, in __get_m3u8_dict
SystemExit: 1

2021-07-20 18:28:38 任务失敗: sn=5791	title="Re：從零開始的異世界生活 [15]" 從任務列隊中移除, 等待下次更新重試.

cookies 6/29那時 有重新抓很多次 都一樣
https://imgur.com/PbA956G

**Comment by 0212908** [comment]
我還是使用22版 22.1不能開
因為我剛剛又看到別人說 刪掉BAHANICK可以識別vip
所以我又用無痕模式提取一次 刪掉BAHANICK還是一樣

**Comment by miyouzi** [comment]
22.1 不能開有報什麽錯誤嗎

**Comment by 0212908** [comment]
無法啟動程式 因為你的電腦遺失api-ms-win-core-path-l1-1-0.dll

**Comment by miyouzi** [comment]
> 無法啟動程式 因為你的電腦遺失api-ms-win-core-path-l1-1-0.dll
> Windows Defender從來沒開過

啊這……Win7 嗎？ 那可能需要網上再這個 dll 了（我的系統也沒有 dll 但是能運行）

或者你選擇源碼運行吧

**Comment by 0212908** [comment]
下載dll後可能沒註冊 所以不能用
可以不可以只下載彈幕 
18+影片的話我自己有方法下載 只是另個方法很麻煩要一個一個下

**Comment by miyouzi** [comment]
> 下載dll後可能沒註冊 所以不能用
> 可以不可以只下載彈幕
> 18+影片的話我自己有方法下載 只是另個方法很麻煩要一個一個下

需要用命令行模式，使用 `-i -d` 參數，另外記得下載 `DanmuTemplate.ass` 檔案放在和 EXE 檔案所在資料夾（或者你再下載一下 release，我剛加進去了）

命令比如：
```
aniGamerPlus.exe -s 23337 -m latest -i -d
```
![image](https://user-images.githubusercontent.com/24269465/126349463-73059fa6-9f23-4280-9c37-03249781c61b.png)

**Comment by 0212908** [comment]
好 謝謝 我會試試
