### ISSUE TITLE
自動更新cookie問題

### ISSUE THREAD

**Issue by jacky013579** [miyouzi/aniGamerPlus#119]
## 問題描述
可以詢問一下,是不是開二重驗證碼就無法自動更新cookie?

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
[2021-07-23.log](https://github.com/miyouzi/aniGamerPlus/files/6867571/2021-07-23.log)

**Comment by miyouzi** [comment]
似乎Cookie刷新的某個Key改了，我需要一些時間來測試

**Comment by YFTX2015** [comment]
遇到同样问题，cookie刷新失败

**Comment by timk-lalala** [comment]
现在好像一天会强制刷新

**Comment by RyanL-29** [comment]
![image](https://user-images.githubusercontent.com/48479346/126885086-7f9f26f3-dc54-4986-9ad8-1e7e858c64f8.png)

好像已經嘗試修復了

基本上就是把 Anime.py 裏面獲取cookie的哪一行

```
                elif 'ANIME_SIGN' in f.headers.get('set-cookie'):
                    # 20210719 动画疯在打开视频时 Cookie 会新增 ANIME_SIGN
                    # https://github.com/miyouzi/aniGamerPlus/issues/110
                    self._cookies['ANIME_SIGN'] = f.cookies.get_dict()['ANIME_SIGN']
                    Config.renew_cookies(self._cookies, log=False)
```

改為

```
                elif 'ANIME_SIGN' in f.headers.get('set-cookie') and 'BAHARUNE' not in f.headers.get('set-cookie'):
                    # 20210719 动画疯在打开视频时 Cookie 会新增 ANIME_SIGN
                    # https://github.com/miyouzi/aniGamerPlus/issues/110
                    self._cookies['ANIME_SIGN'] = f.cookies.get_dict()['ANIME_SIGN']
                    Config.renew_cookies(self._cookies, log=False)
```

**Comment by miyouzi** [comment]
@RyanL-29 除了這個還有一個 `BAHAHASHID` 新的字段，代碼我先push上來了，但是報毒和缺失dll的問題還沒找到解決方法

**Comment by RyanL-29** [comment]
> @RyanL-29 除了這個還有一個 `BAHAHASHID` 新的字段，代碼我先push上來了，但是報毒和缺失dll的問題還沒找到解決方法

報毒和缺失dll真的不知道是什麼問題, 我的python 版本是 3.8.8, 自行構建exe的時候只是會遇到卡巴斯基會把那個程式鎖死十多秒進行掃描, 但很快就放行了. 那麼裏面應該就沒有病毒

**Comment by miyouzi** [comment]
> > @RyanL-29 除了這個還有一個 `BAHAHASHID` 新的字段，代碼我先push上來了，但是報毒和缺失dll的問題還沒找到解決方法
> 
> 報毒和缺失dll真的不知道是什麼問題, 我的python 版本是 3.8.8, 自行構建exe的時候只是會遇到卡巴斯基會把那個程式鎖死十多秒進行掃描, 但很快就放行了. 那麼裏面應該就沒有病毒
> 

我使用的事Python3.9，不清楚是不是版本太高，我等等試試用Python3.8

**Comment by RyanL-29** [comment]
缺失dll 我感覺是應該你這個程式需要Visual C++

https://support.microsoft.com/zh-tw/topic/%E6%9C%80%E6%96%B0%E6%94%AF%E6%8F%B4%E7%9A%84-visual-c-%E4%B8%8B%E8%BC%89-2647da03-1eea-4433-9aff-95f26a218cc0

> > > @RyanL-29 除了這個還有一個 `BAHAHASHID` 新的字段，代碼我先push上來了，但是報毒和缺失dll的問題還沒找到解決方法
> > 
> > 
> > 報毒和缺失dll真的不知道是什麼問題, 我的python 版本是 3.8.8, 自行構建exe的時候只是會遇到卡巴斯基會把那個程式鎖死十多秒進行掃描, 但很快就放行了. 那麼裏面應該就沒有病毒
> 
> 我使用的是Python3.9，不清楚是不是版本太高，我等等試試用Python3.8

**Comment by miyouzi** [comment]
> 缺失dll 我感覺是應該需要Visual C++
> 
> https://support.microsoft.com/zh-tw/topic/%E6%9C%80%E6%96%B0%E6%94%AF%E6%8F%B4%E7%9A%84-visual-c-%E4%B8%8B%E8%BC%89-2647da03-1eea-4433-9aff-95f26a218cc0
> 
> 畢竟我們安裝 Visual Studio Code /Visual Studio 就會自動安裝了, 所以測試起來完全沒有問題
> 
> > > > @RyanL-29 除了這個還有一個 `BAHAHASHID` 新的字段，代碼我先push上來了，但是報毒和缺失dll的問題還沒找到解決方法
> > > 
> > > 
> > > 報毒和缺失dll真的不知道是什麼問題, 我的python 版本是 3.8.8, 自行構建exe的時候只是會遇到卡巴斯基會把那個程式鎖死十多秒進行掃描, 但很快就放行了. 那麼裏面應該就沒有病毒
> > 
> > 我使用的是Python3.9，不清楚是不是版本太高，我等等試試用Python3.8
> 
> 

以前沒有遇到這個問題，就這次遇到有點神奇。

最近我換了新電腦，環境都是新裝的，不知道哪裡踩坑了……

**Comment by RyanL-29** [comment]
剛剛發佈了一個 22.2 測試版本, 已經把Pull Request 都更新進去了, 可以先試一下

https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.2-beta

**Comment by jacky013579** [comment]
> 剛剛發佈了一個 22.2 測試版本, 已經把Pull Request 都更新進去了, 可以先試一下
> 
> https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.2-beta

會報錯
log紀錄:
```
2021-07-25 21:25:07 更新資訊 本次更新添加了 366 個新任務, 目前列隊中共有 366 個任務
2021-07-25 21:25:07 更新终了 
2021-07-25 21:25:08 開始下載: sn=23730	《現實主義勇者的王國重建記 [4]》 識別到VIP賬戶, 立即下載
2021-07-25 21:25:08 開始下載: sn=14258	《卡片戰鬥！！先導者 續高校篇 [13]》 識別到VIP賬戶, 立即下載
2021-07-25 21:25:09 正在下載: sn=23730	現實主義勇者的王國重建記[4][1080P].mp4 title=現實主義勇者的王國重建記 [4]
2021-07-25 21:25:10 正在下載: sn=14258	卡片戰鬥！！先導者 續高校篇[13][1080P].mp4 title=卡片戰鬥！！先導者 續高校篇 [13]
2021-07-25 21:28:41 下載狀態: sn=23730	現實主義勇者的王國重建記[4][1080P].mp4 下載完成, 正在解密合并……
2021-07-25 21:28:41 下載異常: sn=23730	發生未知錯誤: 'add_bangumi_name_to_video_meta'
2021-07-25 21:28:41 下載異常: sn=23730	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 925, in download
  File "Anime.py", line 703, in __segment_download_mode
KeyError: 'add_bangumi_name_to_video_meta'

2021-07-25 21:28:41 解析模式: sn=14259	Web解析
2021-07-25 21:28:41 任务失敗: sn=23730	title="現實主義勇者的王國重建記 [4]" 從任務列隊中移除, 等待下次更新重試.
2021-07-25 21:28:42 開始下載: sn=14259	《卡片戰鬥！！先導者 續高校篇 [14]》 識別到VIP賬戶, 立即下載
2021-07-25 21:28:45 正在下載: sn=14259	卡片戰鬥！！先導者 續高校篇[14][1080P].mp4 title=卡片戰鬥！！先導者 續高校篇 [14]
```

**Comment by miyouzi** [comment]
> add_bangumi_name_to_video_meta

你檢查一下 `config.json` 是 `"add_bangumi_name_to_video_filename"` 不是 `"add_bangumi_name_to_video_meta"`

**Comment by RyanL-29** [comment]
> > add_bangumi_name_to_video_meta
> 
> 你檢查一下 `config.json` 是 `"add_bangumi_name_to_video_filename"` 不是 `"add_bangumi_name_to_video_meta"`

add_bangumi_name_to_video_meta是我自己新增的選項, 你把add_bangumi_name_to_video_meta加進 config.json 然後調成 false 就可以了

**Comment by jacky013579** [comment]
> > > add_bangumi_name_to_video_meta
> > 
> > 
> > 你檢查一下 `config.json` 是 `"add_bangumi_name_to_video_filename"` 不是 `"add_bangumi_name_to_video_meta"`
> 
> add_bangumi_name_to_video_meta是我自己新增的選項, 你把add_bangumi_name_to_video_meta加進 config.json 然後調成 false 就可以了

config.json需要重新載入,無法使用舊檔案
已經可以使用了

**Comment by miyouzi** [comment]
嘗試 v22.2 版本看看

**Comment by newhy** [comment]
中文名字，英文用户名，更新cookies失败 22.3

> 2021-07-31 03:05:24 檢查更新 檢查更新成功
2021-07-31 03:05:24 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v22.3 
2021-07-31 03:05:24 工作目錄: D:\aniGamerPlus_v22.3_windows_64bit 
2021-07-31 03:05:26 刪除過期日志: 2021-07-24.log 
2021-07-31 03:05:28 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2021-07-31 03:05:28 開始更新 
2021-07-31 03:05:28 讀取cookie 發現cookie檔案
2021-07-31 03:05:28 讀取cookie 已讀取cookie
2021-07-31 03:05:28 解析模式: sn=15166	Web解析
2021-07-31 03:05:28 更新資訊: sn=15166	正在檢查《王者天下 第三季》
2021-07-31 03:05:28 解析模式: sn=18433	Web解析
2021-07-31 03:05:29 更新資訊: sn=18433	正在檢查《勇者鬥惡龍 達伊的大冒險》
2021-07-31 03:05:29 解析模式: sn=20527	Web解析
2021-07-31 03:05:29 更新資訊: sn=20527	正在檢查《關於我轉生變成史萊姆這檔事 第二季 [特別篇]》
2021-07-31 03:05:29 解析模式: sn=20620	Web解析
2021-07-31 03:05:29 更新資訊: sn=20620	正在檢查《無職轉生，到了異世界就拿出真本事》
2021-07-31 03:05:29 解析模式: sn=21479	Web解析
2021-07-31 03:05:29 更新資訊: sn=21479	正在檢查《舞伎家的料理人》
2021-07-31 03:05:30 解析模式: sn=22216	Web解析
2021-07-31 03:05:30 更新資訊: sn=22216	正在檢查《義呆利 World Stars》
2021-07-31 03:05:30 解析模式: sn=22219	Web解析
2021-07-31 03:05:30 更新資訊: sn=22219	正在檢查《卡片戰鬥!! 先導者 overdress》
2021-07-31 03:05:30 解析模式: sn=22241	Web解析
2021-07-31 03:05:31 更新資訊: sn=22241	正在檢查《BLUE REFLECTION : 澪》
2021-07-31 03:05:31 解析模式: sn=23546	Web解析
2021-07-31 03:05:31 解析模式: sn=22248	Web解析
2021-07-31 03:05:31 更新資訊: sn=22248	正在檢查《入間同學入魔了 第二季》
2021-07-31 03:05:31 解析模式: sn=22251	Web解析
2021-07-31 03:05:31 更新資訊: sn=22251	正在檢查《東京復仇者 [特別篇]》
2021-07-31 03:05:31 解析模式: sn=22300	Web解析
2021-07-31 03:05:32 更新資訊: sn=22300	正在檢查《給不滅的你》
2021-07-31 03:05:32 解析模式: sn=22333	Web解析
2021-07-31 03:05:32 更新資訊: sn=22333	正在檢查《壽司大相撲》
2021-07-31 03:05:32 解析模式: sn=23272	Web解析
2021-07-31 03:05:32 更新資訊: sn=23272	正在檢查《緋紅結繫》
2021-07-31 03:05:32 解析模式: sn=23333	Web解析
2021-07-31 03:05:32 更新資訊: sn=23333	正在檢查《Love Live! Superstar!!》
2021-07-31 03:05:32 解析模式: sn=23337	Web解析
2021-07-31 03:05:33 更新資訊: sn=23337	正在檢查《急戰 5 秒殊死鬥》
2021-07-31 03:05:33 解析模式: sn=23338	Web解析
2021-07-31 03:05:33 更新資訊: sn=23338	正在檢查《開掛藥師的異世界悠閒生活》
2021-07-31 03:05:33 解析模式: sn=23339	Web解析
2021-07-31 03:05:33 更新資訊: sn=23339	正在檢查《月光下的異世界之旅》
2021-07-31 03:05:33 解析模式: sn=23340	Web解析
2021-07-31 03:05:34 更新資訊: sn=23340	正在檢查《女神宿舍的管理員。 [年齡限制版]》
2021-07-31 03:05:34 解析模式: sn=23342	Web解析
2021-07-31 03:05:34 更新資訊: sn=23342	正在檢查《桃子男孩渡海而來》
2021-07-31 03:05:34 解析模式: sn=23343	Web解析
2021-07-31 03:05:34 更新資訊: sn=23343	正在檢查《暮蟬悲鳴時 卒》
2021-07-31 03:05:34 解析模式: sn=23345	Web解析
2021-07-31 03:05:34 更新資訊: sn=23345	正在檢查《漂流少年》
2021-07-31 03:05:34 解析模式: sn=23346	Web解析
2021-07-31 03:05:34 更新資訊: sn=23346	正在檢查《白沙的 Aquatope》
2021-07-31 03:05:34 解析模式: sn=23347	Web解析
2021-07-31 03:05:35 更新資訊: sn=23347	正在檢查《我立於百萬生命之上 第二季》
2021-07-31 03:05:35 解析模式: sn=23549	Web解析
2021-07-31 03:05:35 解析模式: sn=23348	Web解析
2021-07-31 03:05:35 更新資訊: sn=23348	正在檢查《瓦尼塔斯的手札》
2021-07-31 03:05:35 解析模式: sn=23540	Web解析
2021-07-31 03:05:35 解析模式: sn=23349	Web解析
2021-07-31 03:05:36 更新資訊: sn=23349	正在檢查《叫我對大哥 (TV版)》
2021-07-31 03:05:36 解析模式: sn=23542	Web解析
2021-07-31 03:05:36 解析模式: sn=23350	Web解析
2021-07-31 03:05:36 更新資訊: sn=23350	正在檢查《轉生成女性向遊戲只有毀滅 END 的壞人大小姐 X》
2021-07-31 03:05:36 解析模式: sn=23544	Web解析
2021-07-31 03:05:36 解析模式: sn=23362	Web解析
2021-07-31 03:05:37 更新資訊: sn=23362	正在檢查《魔法科高中的優等生》
2021-07-31 03:05:37 解析模式: sn=23363	Web解析
2021-07-31 03:05:37 更新資訊: sn=23363	正在檢查《RE-MAIN》
2021-07-31 03:05:37 解析模式: sn=23364	Web解析
2021-07-31 03:05:37 更新資訊: sn=23364	正在檢查《現實主義勇者的王國重建記》
2021-07-31 03:05:37 解析模式: sn=23367	Web解析
2021-07-31 03:05:37 更新資訊: sn=23367	正在檢查《蓋特機器人 ARC》
2021-07-31 03:05:37 解析模式: sn=23368	Web解析
2021-07-31 03:05:38 更新資訊: sn=23368	正在檢查《IDOLiSH7 - 偶像星願 - Third BEAT！》
2021-07-31 03:05:38 解析模式: sn=23369	Web解析
2021-07-31 03:05:38 更新資訊: sn=23369	正在檢查《偵探已經，死了。》
2021-07-31 03:05:38 解析模式: sn=23370	Web解析
2021-07-31 03:05:38 更新資訊: sn=23370	正在檢查《闇芝居 第九季》
2021-07-31 03:05:38 解析模式: sn=23373	Web解析
2021-07-31 03:05:38 更新資訊: sn=23373	正在檢查《叫我對大哥 (WEB版)》
2021-07-31 03:05:38 解析模式: sn=23375	Web解析
2021-07-31 03:05:38 更新資訊: sn=23375	正在檢查《我們的重製人生》
2021-07-31 03:05:38 解析模式: sn=23376	Web解析
2021-07-31 03:05:39 更新資訊: sn=23376	正在檢查《死神少爺與黑女僕》
2021-07-31 03:05:39 解析模式: sn=23381	Web解析
2021-07-31 03:05:39 更新資訊: sn=23381	正在檢查《女朋友 and 女朋友》
2021-07-31 03:05:39 解析模式: sn=23552	Web解析
2021-07-31 03:05:39 解析模式: sn=23661	Web解析
2021-07-31 03:05:39 更新資訊: sn=23661	正在檢查《平穩世代的韋駄天們》
2021-07-31 03:05:39 加入任务列隊: sn=23546	
2021-07-31 03:05:39 解析模式: sn=23546	Web解析
2021-07-31 03:05:39 加入任务列隊: sn=23549	
2021-07-31 03:05:39 解析模式: sn=23549	Web解析
2021-07-31 03:05:39 加入任务列隊: sn=23540	
2021-07-31 03:05:39 解析模式: sn=23540	Web解析
2021-07-31 03:05:39 加入任务列隊: sn=23542	
2021-07-31 03:05:39 解析模式: sn=23542	Web解析
2021-07-31 03:05:39 加入任务列隊: sn=23544	
2021-07-31 03:05:39 解析模式: sn=23544	Web解析
2021-07-31 03:05:40 加入任务列隊: sn=23552	
2021-07-31 03:05:40 更新資訊 本次更新添加了 6 個新任務, 目前列隊中共有 6 個任務
2021-07-31 03:05:40 更新终了 
2021-07-31 03:05:40 收到cookie重置響應: sn=23546	
2021-07-31 03:05:40 收到cookie重置響應: sn=23542	
2021-07-31 03:05:40 收到cookie重置響應: sn=23549	
2021-07-31 03:05:40 收到cookie重置響應: sn=23540	
2021-07-31 03:05:40 收到cookie重置響應: sn=23544	
2021-07-31 03:05:42 讀取cookie: sn=23546	cookie.txt最後修改時間: 2021-07-30 07:32:07 第0次嘗試
2021-07-31 03:05:42 讀取cookie: sn=23546	新cookie讀取失敗
2021-07-31 03:05:42 讀取cookie: sn=23542	cookie.txt最後修改時間: 2021-07-30 07:32:07 第0次嘗試
2021-07-31 03:05:42 讀取cookie: sn=23542	新cookie讀取失敗
2021-07-31 03:05:42 讀取cookie: sn=23549	cookie.txt最後修改時間: 2021-07-30 07:32:07 第0次嘗試
2021-07-31 03:05:42 讀取cookie: sn=23549	新cookie讀取失敗
2021-07-31 03:05:42 讀取cookie: sn=23540	cookie.txt最後修改時間: 2021-07-30 07:32:07 第0次嘗試
2021-07-31 03:05:42 讀取cookie: sn=23540	新cookie讀取失敗
2021-07-31 03:05:42 讀取cookie: sn=23544	cookie.txt最後修改時間: 2021-07-30 07:32:07 第0次嘗試
2021-07-31 03:05:42 讀取cookie: sn=23544	新cookie讀取失敗
2021-07-31 03:05:45 讀取cookie: sn=23549	cookie.txt最後修改時間: 2021-07-30 07:32:07 第1次嘗試
2021-07-31 03:05:45 讀取cookie: sn=23549	新cookie讀取失敗
2021-07-31 03:05:46 讀取cookie: sn=23546	cookie.txt最後修改時間: 2021-07-30 07:32:07 第1次嘗試
2021-07-31 03:05:46 讀取cookie: sn=23546	新cookie讀取失敗
2021-07-31 03:05:46 讀取cookie: sn=23544	cookie.txt最後修改時間: 2021-07-30 07:32:07 第1次嘗試
2021-07-31 03:05:46 讀取cookie: sn=23544	新cookie讀取失敗
2021-07-31 03:05:46 讀取cookie: sn=23540	cookie.txt最後修改時間: 2021-07-30 07:32:07 第1次嘗試
2021-07-31 03:05:46 讀取cookie: sn=23540	新cookie讀取失敗
2021-07-31 03:05:47 讀取cookie: sn=23542	cookie.txt最後修改時間: 2021-07-30 07:32:07 第1次嘗試
2021-07-31 03:05:47 讀取cookie: sn=23542	新cookie讀取失敗
2021-07-31 03:05:48 讀取cookie: sn=23546	cookie.txt最後修改時間: 2021-07-30 07:32:07 第2次嘗試
2021-07-31 03:05:48 讀取cookie: sn=23546	新cookie讀取失敗
2021-07-31 03:05:49 讀取cookie: sn=23544	cookie.txt最後修改時間: 2021-07-30 07:32:07 第2次嘗試
2021-07-31 03:05:49 讀取cookie: sn=23544	新cookie讀取失敗
2021-07-31 03:05:50 讀取cookie: sn=23540	cookie.txt最後修改時間: 2021-07-30 07:32:07 第2次嘗試
2021-07-31 03:05:50 讀取cookie: sn=23540	新cookie讀取失敗
2021-07-31 03:05:50 讀取cookie: sn=23542	cookie.txt最後修改時間: 2021-07-30 07:32:07 第2次嘗試
2021-07-31 03:05:50 讀取cookie: sn=23542	新cookie讀取失敗
2021-07-31 03:05:50 讀取cookie: sn=23549	cookie.txt最後修改時間: 2021-07-30 07:32:07 第2次嘗試
2021-07-31 03:05:50 讀取cookie: sn=23549	新cookie讀取失敗
2021-07-31 03:05:51 用戶cookie更新失敗! 使用游客身份訪問 
2021-07-31 03:05:51 cookie狀態 已成功標記失效cookie
2021-07-31 03:05:52 正在等待: sn=23544	《轉生成女性向遊戲只有毀滅 END 的壞人大小姐 X [5]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-07-31 03:05:53 用戶cookie更新失敗! 使用游客身份訪問 
2021-07-31 03:05:54 正在等待: sn=23546	《BLUE REFLECTION : 澪 [16]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-07-31 03:05:54 用戶cookie更新失敗! 使用游客身份訪問 
2021-07-31 03:05:54 用戶cookie更新失敗! 使用游客身份訪問 
2021-07-31 03:05:54 正在等待: sn=23542	《叫我對大哥 (TV版) [5]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-07-31 03:05:54 正在等待: sn=23549	《我立於百萬生命之上 第二季 [16]》 由於不是VIP賬戶, 正在等待25s廣告時間
2021-07-31 03:05:55 用戶cookie更新失敗! 使用游客身份訪問 
2021-07-31 03:05:55 正在等待: sn=23540	《瓦尼塔斯的手札 [5]》 由於不是VIP賬戶, 正在等待25s廣告時間

**Comment by miyouzi** [comment]
@newhy 检查UA是否是取得Cookie的浏览器UA，以及cookie是否是从无痕模式取得。

**Comment by newhy** [comment]
@miyouzi 的确是UA问题，现在用无痕模式cookie也能更新
