### ISSUE TITLE
dashboard 在新版本裡無法打開

### ISSUE THREAD

**Issue by tinlans** [miyouzi/aniGamerPlus#132]
## 問題描述

v22.0 的 dashboard 還能正常從瀏覽器 127.0.0.1:5000 打開，更新成 v22.3 或 v22.51 後瀏覽器出現 500 Internal Server Error。
作業系統是 Windows 7 SP1 x64。

## 錯誤截圖

錯誤訊息很長，截圖無法完整呈現，我去 web.log 裡複製出來。

```
Exception on / [GET]
Traceback (most recent call last):
  File "flask_sockets.py", line 40, in __call__
  File "werkzeug\routing.py", line 1945, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "Dashboard\Server.py", line 93, in home
    return render_template('index.html')
  File "flask\templating.py", line 138, in render_template
  File "jinja2\environment.py", line 930, in get_or_select_template
  File "jinja2\environment.py", line 883, in get_template
  File "jinja2\environment.py", line 857, in _load_template
  File "jinja2\loaders.py", line 115, in load
  File "flask\templating.py", line 60, in get_source
  File "flask\templating.py", line 89, in _get_source_fast
jinja2.exceptions.TemplateNotFound: index.html
```

確定檔案是完整的，目錄結構沒有動過，我解壓縮到一個空白目錄去執行也是一樣的問題。

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 4,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": "",
    "only_use_vip": true
}
```

## sn_list.txt 配置
```
# 內容空白
```

**Comment by miyouzi** [comment]
你在 CMD 裏運行 `tree /F "你的aniGamerPlus存放的資料夾"` 然後把顯示的内容粘貼過來。

比如：你把程式放在了 `D:\Temp\aniGamerPlus_v22.51_windows_64bit`，那麽運行 `tree -F "D:\Temp\aniGamerPlus_v22.51_windows_64bit"`

**Comment by tinlans** [comment]
> 
> 
> 你在 CMD 裏運行 `tree /F "你的aniGamerPlus存放的資料夾"` 然後把顯示的内容粘貼過來。
> 
> 比如：你把程式放在了 `D:\Temp\aniGamerPlus_v22.51_windows_64bit`，那麽運行 `tree /F "D:\Temp\aniGamerPlus_v22.51_windows_64bit"`

```
D:\ANIGAMERPLUS
│  aniGamer.db
│  aniGamerPlus.exe
│  config.json
│  cookie.txt
│  DanmuTemplate.ass
│  ffmpeg.exe
│  LICENSE
│  list.txt
│  README.md
│  sn_list.txt
│  
├─bangumi
│          
├─Dashboard
│  │  Server.py
│  │  
│  ├─sslkey
│  │      server.crt
│  │      server.key
│  │      
│  ├─static
│  │  ├─css
│  │  │      aniGamerPlus.css
│  │  │      bootstrap-select.min.css
│  │  │      bootstrap-switch.min.css
│  │  │      bootstrap.min.css
│  │  │      bootstrap.rfs.min.css
│  │  │      fontawesome.all.min.css
│  │  │      
│  │  ├─img
│  │  │      aniGamerPlus.ico
│  │  │      
│  │  ├─js
│  │  │      aniGamerPlus.js
│  │  │      bootstrap-select.min.js
│  │  │      bootstrap-switch.min-3.3.4.js
│  │  │      bootstrap.min.js
│  │  │      jquery-3.4.0.min.js
│  │  │      monitor.js
│  │  │      popper.min.js
│  │  │      settings_id_list.js
│  │  │      
│  │  ├─layui
│  │  │  │  layui.all.js
│  │  │  │  layui.js
│  │  │  │  
│  │  │  ├─css
│  │  │  │  │  layui.css
│  │  │  │  │  layui.mobile.css
│  │  │  │  │  
│  │  │  │  └─modules
│  │  │  │      │  code.css
│  │  │  │      │  
│  │  │  │      ├─laydate
│  │  │  │      │  └─default
│  │  │  │      │          laydate.css
│  │  │  │      │          
│  │  │  │      └─layer
│  │  │  │          └─default
│  │  │  │                  icon-ext.png
│  │  │  │                  icon.png
│  │  │  │                  layer.css
│  │  │  │                  loading-0.gif
│  │  │  │                  loading-1.gif
│  │  │  │                  loading-2.gif
│  │  │  │                  
│  │  │  ├─font
│  │  │  │      iconfont.eot
│  │  │  │      iconfont.svg
│  │  │  │      iconfont.ttf
│  │  │  │      iconfont.woff
│  │  │  │      iconfont.woff2
│  │  │  │      
│  │  │  ├─images
│  │  │  │  └─face
│  │  │  │          0.gif
│  │  │  │          1.gif
│  │  │  │          10.gif
│  │  │  │          11.gif
│  │  │  │          12.gif
│  │  │  │          13.gif
│  │  │  │          14.gif
│  │  │  │          15.gif
│  │  │  │          16.gif
│  │  │  │          17.gif
│  │  │  │          18.gif
│  │  │  │          19.gif
│  │  │  │          2.gif
│  │  │  │          20.gif
│  │  │  │          21.gif
│  │  │  │          22.gif
│  │  │  │          23.gif
│  │  │  │          24.gif
│  │  │  │          25.gif
│  │  │  │          26.gif
│  │  │  │          27.gif
│  │  │  │          28.gif
│  │  │  │          29.gif
│  │  │  │          3.gif
│  │  │  │          30.gif
│  │  │  │          31.gif
│  │  │  │          32.gif
│  │  │  │          33.gif
│  │  │  │          34.gif
│  │  │  │          35.gif
│  │  │  │          36.gif
│  │  │  │          37.gif
│  │  │  │          38.gif
│  │  │  │          39.gif
│  │  │  │          4.gif
│  │  │  │          40.gif
│  │  │  │          41.gif
│  │  │  │          42.gif
│  │  │  │          43.gif
│  │  │  │          44.gif
│  │  │  │          45.gif
│  │  │  │          46.gif
│  │  │  │          47.gif
│  │  │  │          48.gif
│  │  │  │          49.gif
│  │  │  │          5.gif
│  │  │  │          50.gif
│  │  │  │          51.gif
│  │  │  │          52.gif
│  │  │  │          53.gif
│  │  │  │          54.gif
│  │  │  │          55.gif
│  │  │  │          56.gif
│  │  │  │          57.gif
│  │  │  │          58.gif
│  │  │  │          59.gif
│  │  │  │          6.gif
│  │  │  │          60.gif
│  │  │  │          61.gif
│  │  │  │          62.gif
│  │  │  │          63.gif
│  │  │  │          64.gif
│  │  │  │          65.gif
│  │  │  │          66.gif
│  │  │  │          67.gif
│  │  │  │          68.gif
│  │  │  │          69.gif
│  │  │  │          7.gif
│  │  │  │          70.gif
│  │  │  │          71.gif
│  │  │  │          8.gif
│  │  │  │          9.gif
│  │  │  │          
│  │  │  └─lay
│  │  │      └─modules
│  │  │              carousel.js
│  │  │              code.js
│  │  │              colorpicker.js
│  │  │              element.js
│  │  │              flow.js
│  │  │              form.js
│  │  │              jquery.js
│  │  │              laydate.js
│  │  │              layedit.js
│  │  │              layer.js
│  │  │              laypage.js
│  │  │              laytpl.js
│  │  │              mobile.js
│  │  │              rate.js
│  │  │              slider.js
│  │  │              table.js
│  │  │              transfer.js
│  │  │              tree.js
│  │  │              upload.js
│  │  │              util.js
│  │  │              
│  │  └─webfonts
│  │          fa-brands-400.eot
│  │          fa-brands-400.svg
│  │          fa-brands-400.ttf
│  │          fa-brands-400.woff
│  │          fa-brands-400.woff2
│  │          fa-regular-400.eot
│  │          fa-regular-400.svg
│  │          fa-regular-400.ttf
│  │          fa-regular-400.woff
│  │          fa-regular-400.woff2
│  │          fa-solid-900.eot
│  │          fa-solid-900.svg
│  │          fa-solid-900.ttf
│  │          fa-solid-900.woff
│  │          fa-solid-900.woff2
│  │          
│  ├─templates
│  │      index.html
│  │      login.html
│  │      monitor.html
│  │      register.html
│  │      
│  └─__pycache__
│          Server.cpython-39.pyc
│          
├─logs
│      2021-03-21.log
│      2021-03-22.log
│      2021-09-07.log
│      2021-09-08.log
│      web.log
│      web.log.2021-03-21.log
│      web.log.2021-03-22.log
│      web.log.2021-09-07.log
│      
└─temp

```

**Comment by miyouzi** [comment]
爲什麽有這個問題還是沒什麽思路，你使用源碼運行試試看好了
