### ISSUE TITLE
無法下載影片

### ISSUE THREAD

**Issue by Laputa-Skywalker** [miyouzi/aniGamerPlus#138]
## 錯誤截圖
[https://i.imgur.com/6JZzJBp.png](url)
## config.json 配置
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0
}
```

**最好上傳 log 檔案**

2021-11-22 00:02:49 Dashboard 通過 Web 控制臺下達了手動任務
2021-11-22 00:02:49 解析模式: sn=3499	Web解析
2021-11-22 00:03:01 任務狀態: sn=3499	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=3499 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012DA85529D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
3s后重试(最多重试3次)
2021-11-22 00:03:14 開始更新 
2021-11-22 00:03:14 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:03:14 更新终了 
2021-11-22 00:03:16 任務狀態: sn=3499	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=3499 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012DA856D340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
3s后重试(最多重试3次)
2021-11-22 00:03:31 任務狀態: sn=3499	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=3499 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012DA85AAD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
3s后重试(最多重试3次)
2021-11-22 00:03:34 抓取失敗: sn=3499	影片信息抓取失敗!
2021-11-22 00:05:50 Dashboard 通過 Web 控制臺下達了手動任務
2021-11-22 00:05:50 解析模式: sn=3499	Web解析
2021-11-22 00:05:50 收到新cookie: sn=3499	
2021-11-22 00:05:50 新cookie保存成功 
2021-11-22 00:05:51 用戶cookie已更新 
2021-11-22 00:05:51 開始下載: sn=3499	《進擊的巨人 [1]》 識別到VIP賬戶, 立即下載
2021-11-22 00:05:52 正在下載: sn=3499	【動畫瘋】進擊的巨人[1][1080P].mp4 title=進擊的巨人 [1]
2021-11-22 00:07:32 下載狀態: sn=3499	【動畫瘋】進擊的巨人[1][1080P].mp4 下載完成, 正在解密合并……
2021-11-22 00:07:32 下載異常: sn=3499	發生未知異常: [WinError 2] 系統找不到指定的檔案。: 'C:\\Users\\User\\Downloads\\aniGamerPlus_v22.51_windows_64bit\\temp\\【動畫瘋】進擊的巨人[1][1080P].MERGING.mp4'
2021-11-22 00:07:32 下載異常: sn=3499	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 343, in __download_only
  File "Anime.py", line 906, in download
  File "Anime.py", line 702, in __segment_download_mode
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'C:\\Users\\User\\Downloads\\aniGamerPlus_v22.51_windows_64bit\\temp\\【動畫瘋】進擊的巨人[1][1080P].MERGING.mp4'

2021-11-22 00:07:32 任務失敗: sn=3499	title=進擊的巨人 [1] 10s后自動重啓,最多重試三次
2021-11-22 00:08:15 開始更新 
2021-11-22 00:08:15 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:08:15 更新终了 
2021-11-22 00:10:05 Dashboard 通過 Web 控制臺下達了手動任務
2021-11-22 00:10:05 解析模式: sn=3499	Web解析
2021-11-22 00:10:06 開始下載: sn=3499	《進擊的巨人 [1]》 識別到VIP賬戶, 立即下載
2021-11-22 00:10:07 正在下載: sn=3499	【動畫瘋】進擊的巨人[1][1080P].mp4 title=進擊的巨人 [1]
2021-11-22 00:11:48 下載狀態: sn=3499	【動畫瘋】進擊的巨人[1][1080P].mp4 下載完成, 正在解密合并……
2021-11-22 00:11:48 下載異常: sn=3499	發生未知異常: [WinError 2] 系統找不到指定的檔案。: 'C:\\Users\\User\\Downloads\\aniGamerPlus_v22.51_windows_64bit\\temp\\【動畫瘋】進擊的巨人[1][1080P].MERGING.mp4'
2021-11-22 00:11:48 下載異常: sn=3499	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 343, in __download_only
  File "Anime.py", line 906, in download
  File "Anime.py", line 702, in __segment_download_mode
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'C:\\Users\\User\\Downloads\\aniGamerPlus_v22.51_windows_64bit\\temp\\【動畫瘋】進擊的巨人[1][1080P].MERGING.mp4'

2021-11-22 00:11:48 任務失敗: sn=3499	title=進擊的巨人 [1] 10s后自動重啓,最多重試三次
2021-11-22 00:13:15 開始更新 
2021-11-22 00:13:15 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:13:15 更新终了 
2021-11-22 00:18:15 開始更新 
2021-11-22 00:18:15 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:18:15 更新终了 
2021-11-22 00:23:16 開始更新 
2021-11-22 00:23:16 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:23:16 更新终了 
2021-11-22 00:28:16 開始更新 
2021-11-22 00:28:16 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2021-11-22 00:28:16 更新终了

**Comment by miyouzi** [comment]
檢查 FFmpeg 是否存在
