### ISSUE TITLE
收到新cookie後的檢查, 會有錯誤導致cookie遺失

### ISSUE THREAD

**Issue by RyanL-29** [miyouzi/aniGamerPlus#144]
## 問題描述
如題

## 錯誤截圖
![image](https://user-images.githubusercontent.com/48479346/146771239-25aea335-7bbc-47d7-92c5-788d891990d3.png)

**最好上傳 log 檔案**

```
2021-12-20 20:45:11 更新資訊: sn=25569	正在檢查《獻身給魔王伊伏洛基亞吧》
2021-12-20 20:45:11 解析模式: sn=25458	Web解析
2021-12-20 20:45:11 更新資訊: sn=25458	正在檢查《異世界食堂 2》
2021-12-20 20:45:11 解析模式: sn=25479	Web解析
2021-12-20 20:45:11 更新資訊: sn=25479	正在檢查《結城友奈是勇者 大滿開之章》
2021-12-20 20:45:11 解析模式: sn=25557	Web解析
2021-12-20 20:45:12 更新資訊: sn=25557	正在檢查《燒窯的話也要馬克杯 第二季》
2021-12-20 20:45:12 解析模式: sn=21781	Web解析
2021-12-20 20:45:12 收到新cookie: sn=21781	
2021-12-20 20:45:12 新cookie保存成功 
2021-12-20 20:45:12 用戶cookie已更新 
2021-12-20 20:45:12 ERROR: 該 sn 下真的有動畫？: sn=21781	
2021-12-20 20:45:12 抓取失敗: sn=21781	抓取影片信息時發生未知錯誤: 1
2021-12-20 20:45:13 抓取異常: sn=21781	異常詳情:
Traceback (most recent call last):
  File "Anime.py", line 134, in __get_title
AttributeError: 'NoneType' object has no attribute 'h1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 53, in build_anime
  File "Anime.py", line 64, in __init__
  File "Anime.py", line 139, in __get_title
SystemExit: 1

```
應該是檢查太有規律, 被 CF Bot盾擋了

**Comment by RyanL-29** [comment]
正在調查是否因為有雙重驗證所以出現問題

**Comment by RyanL-29** [comment]
> 正在調查是否因為有雙重驗證所以出現問題

並不是繼續調查中

**Comment by miyouzi** [comment]
等下嘗試 v22.7 版本

**Comment by sayo10350035** [comment]
你好，我遇到相同的問題，而且已經更新至v22.7版本，狀況還是未改善
![圖片](https://user-images.githubusercontent.com/98143436/150471053-66289cf2-f804-4466-b8c5-cad169ecb274.png)
每過幾一段時間，cookie就會失效
更新至v22.7前，cookie.txt會變成短短一行字
更新至v22.7後，cookie.txt檔案會直接消失

**Comment by miyouzi** [comment]
> 你好，我遇到相同的問題，而且已經更新至v22.7版本，狀況還是未改善
> ![圖片](https://user-images.githubusercontent.com/98143436/150471053-66289cf2-f804-4466-b8c5-cad169ecb274.png)
> 每過幾一段時間，cookie就會失效
> 更新至v22.7前，cookie.txt會變成短短一行字
> 更新至v22.7後，cookie.txt檔案會直接消失

你檢查一下 UA 配置是不是你獲取 cookie 的瀏覽器的 UA，確認過後重新在無痕模式取的 cookie 再試試
