### ISSUE TITLE
下載指定範圍番劇時適逢更新 cookie 會導致下載失敗

### ISSUE THREAD

**Issue by i1itione** [miyouzi/aniGamerPlus#151]
## 問題描述
剛好在要下載我指定的範圍的最後一集時，進行了 cookie 的更新，接著就下載失敗了。
之後指定單集 sn 重新下載則順利完成。可能是在更新 cookie 的時候發生了什麼問題？

下載指定範圍時使用的指令：
aniGamerPlus -s 26501 -m sn-range -e 27498-27535,27537-27554

發生錯誤後重新下載單集用的指令：
aniGamerPlus -s 27554

以下是錯誤訊息：

2022-01-10 00:18:19 正在等待: sn=27554	《名偵探柯南 [802] [中文配音]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-01-10 00:18:29 任務狀態: sn=27554	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Read timed out. (read timeout=10)
3s后重试(最多重试3次)
2022-01-10 00:18:33 收到新cookie: sn=27554	
2022-01-10 00:18:33 新cookie保存成功 
2022-01-10 00:18:33 用戶cookie已更新 
2022-01-10 00:18:58 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 10: sn=27554	
2022-01-10 00:19:00 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 9: sn=27554	
2022-01-10 00:19:02 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 8: sn=27554	
2022-01-10 00:19:04 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 7: sn=27554	
2022-01-10 00:19:06 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 6: sn=27554	
2022-01-10 00:19:09 收到新cookie: sn=27554	
2022-01-10 00:19:09 新cookie保存成功 
2022-01-10 00:19:09 用戶cookie已更新 
2022-01-10 00:19:09 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 5: sn=27554	
2022-01-10 00:19:11 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 4: sn=27554	
2022-01-10 00:19:13 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 3: sn=27554	
2022-01-10 00:19:15 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 2: sn=27554	
2022-01-10 00:19:17 廣告似乎還沒去除, 追加等待2秒, 剩餘重試次數 1: sn=27554	
2022-01-10 00:19:20 廣告去除失敗! 請向開發者提交 issue!: sn=27554	
2022-01-10 00:19:20 下載異常: sn=27554	發生未知異常: 1
2022-01-10 00:19:20 下載異常: sn=27554	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 343, in __download_only
  File "Anime.py", line 839, in download
  File "Anime.py", line 509, in __get_m3u8_dict
  File "Anime.py", line 441, in check_no_ad
  File "Anime.py", line 441, in check_no_ad
  File "Anime.py", line 441, in check_no_ad
  [Previous line repeated 7 more times]
  File "Anime.py", line 429, in check_no_ad
SystemExit: 1

2022-01-10 00:19:20 任務失敗: sn=27554	title=名偵探柯南 [802] [中文配音] 10s后自動重啓,最多重試三次

**Comment by miyouzi** [comment]
麻煩上傳一下 config.json 然後檢查一下 cookie 是不是變成短短的幾個字

**Comment by i1itione** [comment]
> 麻煩上傳一下 config.json 然後檢查一下 cookie 是不是變成短短的幾個字

真的耶，cookie.txt 的內容只剩下一行：
cf_use_ob=0

底下是 config.json（方便上傳我加了 .txt 後綴）
[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/7840052/config.json.txt)

**Comment by miyouzi** [comment]
已知問題，修復中（最新commit有嘗試修了，急的話用源碼，或者去action下載ci包）

**Comment by miyouzi** [comment]
等下嘗試 v22.7 版本
