### ISSUE TITLE
run docker image時 jinja2 import錯誤

### ISSUE THREAD

**Issue by mitsuki105** [miyouzi/aniGamerPlus#160]
## 問題描述

在run官方docker image ·tonypepe/anigamerplus·時 發生以下錯誤。 

```
當前aniGamerPlus版本: v22.7

Traceback (most recent call last):

  File "/app/aniGamerPlus.py", line 859, in <module>

    run_dashboard()

  File "/app/aniGamerPlus.py", line 680, in run_dashboard

    from Dashboard.Server import run as dashboard

  File "/app/Dashboard/Server.py", line 17, in <module>

    from flask import Flask, request, jsonify

  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>

    from jinja2 import escape

  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>

    from .environment import Environment

  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>

    from .defaults import BLOCK_END_STRING

  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>

    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401

  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>

    from markupsafe import soft_unicode

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)
```

**Comment by miyouzi** [comment]
咨詢一下 @TonyPepeBear
