### ISSUE TITLE
無法下載動畫~

### ISSUE THREAD

**Issue by leslie100791** [miyouzi/aniGamerPlus#173]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
無法下載動畫~

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/88264590/160667569-aa31e1a3-4023-476c-a330-f448bfd55f62.png)

## config.json 配置
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16,
    "database_version": 2.0
}
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```


**最好上傳 log 檔案**
127.0.0.1 - - [2022-03-30 01:07:29] "GET / HTTP/1.1" 200 18470 0.000000
127.0.0.1 - - [2022-03-30 01:07:29] "GET /data/config.json HTTP/1.1" 200 1039 0.001007
127.0.0.1 - - [2022-03-30 01:07:29] "GET /data/sn_list HTTP/1.1" 200 115 0.000000
Exception on /manualTask [POST]
Traceback (most recent call last):
  File "flask_sockets.py", line 40, in __call__
  File "werkzeug\routing.py", line 1945, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "Dashboard\Server.py", line 141, in manual_task
    thread = int(data['thread'])
ValueError: invalid literal for int() with base 10: ''
127.0.0.1 - - [2022-03-30 01:07:46] "POST /manualTask HTTP/1.1" 500 426 0.004982
127.0.0.1 - - [2022-03-30 01:09:03] "GET / HTTP/1.1" 200 18470 0.004983
127.0.0.1 - - [2022-03-30 01:09:03] "GET /data/config.json HTTP/1.1" 200 1039 0.001002
127.0.0.1 - - [2022-03-30 01:09:03] "GET /data/sn_list HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2022-03-30 01:09:04] "GET / HTTP/1.1" 200 18470 0.000000
127.0.0.1 - - [2022-03-30 01:09:04] "GET /data/config.json HTTP/1.1" 200 1039 0.001988
127.0.0.1 - - [2022-03-30 01:09:04] "GET /data/sn_list HTTP/1.1" 200 115 0.001279
127.0.0.1 - - [2022-03-30 01:09:04] "GET / HTTP/1.1" 200 18470 0.000000
127.0.0.1 - - [2022-03-30 01:09:04] "GET /data/config.json HTTP/1.1" 200 1039 0.000000
127.0.0.1 - - [2022-03-30 01:09:04] "GET /data/sn_list HTTP/1.1" 200 115 0.000000
Exception on /manualTask [POST]
Traceback (most recent call last):
  File "flask_sockets.py", line 40, in __call__
  File "werkzeug\routing.py", line 1945, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "Dashboard\Server.py", line 141, in manual_task
    thread = int(data['thread'])
ValueError: invalid literal for int() with base 10: ''
127.0.0.1 - - [2022-03-30 01:09:16] "POST /manualTask HTTP/1.1" 500 426 0.001993

**Comment by leslie100791** [comment]
如果有甚麼不夠詳細的地方可以再告訴我~

**Comment by kirbyloco** [comment]
@leslie100791 
看你的Log應該是缺少"最大併發下載數"，
至少要填1才會正常。
![image](https://user-images.githubusercontent.com/17351171/160727143-89b7d7b9-cbf1-4385-bb92-1238888f65f8.png)

**Comment by leslie100791** [comment]
了解~我試試看!
