### ISSUE TITLE
影片可正常下載，但無法下載字幕，且無法順利完成任務

### ISSUE THREAD

**Issue by hwakeyeTW** [miyouzi/aniGamerPlus#175]
## 問題描述
字幕下載失敗，Log提示錯誤訊息
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 887, in download
TypeError: __init__() missing 1 required positional argument: 'cookies'

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![圖片](https://user-images.githubusercontent.com/102696847/160922738-14b0f14c-3f6f-4c87-a4dd-8fd797b43ae1.png)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": true,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.5",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": true,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16,
    "database_version": 2.0,
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "danmu_ban_words": []
}
```

## sn_list.txt 配置
```
@超人力霸王
11812 all #超人力霸王 X
```

**最好上傳 log 檔案**
[2022-03-31.log](https://github.com/miyouzi/aniGamerPlus/files/8383788/2022-03-31.log)

**Comment by hwakeyeTW** [comment]
是彈幕無法下載沒錯，沒注意到原來已經有修正了，感謝通知！
