### ISSUE TITLE
無法啟動

### ISSUE THREAD

**Issue by tommykhy** [miyouzi/aniGamerPlus#241]
E:\Program Files\aniGamerPlus_v24.5_windows_64bit>aniGamerPlus.exe
Traceback (most recent call last):
  File "aniGamerPlus.py", line 842, in <module>
  File "Config.py", line 524, in read_settings
  File "Config.py", line 390, in __update_settings
PermissionError: [Errno 13] Permission denied: 'E:\\Program Files\\aniGamerPlus_v24.5_windows_64bit\\config.json'
[28396] Failed to execute script 'aniGamerPlus' due to unhandled exception!

**Comment by miyouzi** [comment]
權限問題，換個資料夾試試？
