### ISSUE TITLE
抓取影片信息時發生未知錯誤: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by shokuhou0** [miyouzi/aniGamerPlus#245]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![QQ图片20230507034553](https://user-images.githubusercontent.com/97113587/236643794-4224b8c7-3294-4ae6-9e64-522782fe5b82.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "use_proxy": true,
    "proxy": "socks5://2l3o8Zs756:E92D9Ccmh7@36.227.198.200:10070",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

2023-05-07 03:44:52 檢查更新 檢查更新失敗
2023-05-07 03:44:52 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v24.5 
2023-05-07 03:44:52 工作目錄: C:\Users\12480\Desktop\aniGamerPlus_v24.5_windows_64bit 
2023-05-07 03:44:56 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2023-05-07 03:44:56 開始更新 
2023-05-07 03:44:56 讀取cookie 未發現cookie檔案
2023-05-07 03:44:56 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2023-05-07 03:44:56 更新终了 
2023-05-07 03:45:13 Dashboard 通過 Web 控制臺下達了手動任務
2023-05-07 03:45:13 解析模式: sn=27978	Web解析
2023-05-07 03:45:13 抓取失敗: sn=27978	抓取影片信息時發生未知錯誤: not enough values to unpack (expected 3, got 1)
2023-05-07 03:45:13 抓取異常: sn=27978	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 55, in build_anime
  File "Anime.py", line 73, in __init__
  File "Anime.py", line 141, in __get_src
  File "Anime.py", line 285, in __request
  File "pyhttpx\session.py", line 285, in get
  File "pyhttpx\session.py", line 175, in request
  File "pyhttpx\session.py", line 246, in send
  File "pyhttpx\session.py", line 240, in get_conn
  File "pyhttpx\session.py", line 81, in _get_conn
  File "pyhttpx\session.py", line 71, in _new_conn
  File "pyhttpx\layers\tls\pyssl.py", line 119, in connect
  File "pyhttpx\layers\tls\socks.py", line 53, in connect
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by miyouzi** [comment]
pyhttpx套件的問題，其他電腦會出現這個問題嗎？

**Comment by shokuhou0** [comment]
我试了笔记本也是这样

**Comment by shokuhou0** [comment]
> pyhttpx套件的問題，其他電腦會出現這個問題嗎？

我试了笔记本也是这样
