### ISSUE TITLE
抓取失敗: sn=34030  抓取影片信息時發生未知錯誤: 'BAHARUNE'

### ISSUE THREAD

**Issue by jim12050521** [miyouzi/aniGamerPlus#280]
## 問題描述
#照的部落格指示試了很多遍，但還是不行下載。
抓取失敗: sn=34030  抓取影片信息時發生未知錯誤: 'BAHARUNE'

## 錯誤截圖
[#]
![螢幕擷取畫面 2024-09-07 040226](https://github.com/user-attachments/assets/5065f97e-bc29-4f70-8660-94dfa04aefd5)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": false,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.1,
    "database_version": 2.0,
    "classify_season": false,
    "plex_naming": false,
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "danmu_ban_words": []
}
```

## sn_list.txt 配置(未使用)
```
```

**最好上傳 log 檔案**
log:(單次)
2024-09-07 03:41:05 開始更新 
2024-09-07 03:41:05 讀取cookie 發現cookie檔案
2024-09-07 03:41:05 讀取cookie 已讀取cookie
2024-09-07 03:41:05 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2024-09-07 03:41:05 更新终了 
2024-09-07 03:42:03 Dashboard 通過 Web 控制臺更新了 config.json
2024-09-07 03:42:15 Dashboard 通過 Web 控制臺下達了手動任務
2024-09-07 03:42:15 解析模式: sn=34030	Web解析
2024-09-07 03:42:16 收到新cookie: sn=34030	
2024-09-07 03:42:16 用戶cookie刷新  : sn=34030	
2024-09-07 03:42:16 收到cookie重置響應: sn=34030	
2024-09-07 03:42:18 抓取失敗: sn=34030	抓取影片信息時發生未知錯誤: 'BAHARUNE'
2024-09-07 03:42:18 抓取異常: sn=34030	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 55, in build_anime
  File "Anime.py", line 73, in __init__
  File "Anime.py", line 141, in __get_src
  File "Anime.py", line 361, in __request
  File "Anime.py", line 326, in __request
KeyError: 'BAHARUNE'

**Comment by jim12050521** [comment]
我非常希望能解決，如果還有甚麼判斷依據，敬請提出來，謝謝大家。

**Comment by ilolipopi** [comment]
相同错误。一段或许更详细的错误日志：
```
2026-05-12 02:14:09 檢查更新 檢查更新成功
2026-05-12 02:14:09 使用命令行模式, 文件將保存在配置文件中指定的目錄下: Downloads/softwares/aniGamerPlus/bangumi 
2026-05-12 02:14:09 讀取cookie 發現cookie檔案
2026-05-12 02:14:09 讀取cookie 已讀取cookie
2026-05-12 02:14:09 解析模式: sn=19238	APP解析
2026-05-12 02:14:10 SN 解析冷卻 5 秒 
2026-05-12 02:14:15 嘗試切換回 Web Header 刷新 Cookie: sn=19238	
2026-05-12 02:14:16 收到cookie重置響應: sn=19238	
2026-05-12 02:14:18 下載異常: sn=19238	發生未知異常: 'BAHARUNE'
2026-05-12 02:14:18 下載異常: sn=19238	異常詳情:
Traceback (most recent call last):
  File "Downloads/softwares/aniGamerPlus/aniGamerPlus.py", line 406, in __download_only
    anime.download(dl_resolution, dl_save_dir, realtime_show_file_size=realtime_show_file_size, classify=classify)
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 895, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 480, in __get_m3u8_dict
    get_device_id()
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 380, in get_device_id
    self._device_id = self.__request_json(req)['deviceid']
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 374, in __request_json
    return self.__request(req, no_cookies, show_fail, max_retry, addition_header, use_pyhttpx).json()
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 317, in __request
    self.__request('https://ani.gamer.com.tw/')  # 再次尝试获取新 cookie
  File "Downloads/softwares/aniGamerPlus/Anime.py", line 324, in __request
    old_BAHARUNE = self._cookies['BAHARUNE']
KeyError: 'BAHARUNE'

2026-05-12 02:14:18 任務失敗: sn=19238	title=名偵探柯南 [943] [中文配音] 10s后自動重啓,最多重試三次
2026-05-12 02:14:28 收到cookie重置響應: sn=19238	
2026-05-12 02:14:30 下載異常: sn=19238	發生未知異常: 'BAHARUNE'
2026-05-12 02:14:30 下載異常: sn=19238	異常詳情:
```
环境：python3.9, Arch linux with kernel 7.0.4
```
uv pip list
Package            Version
------------------ ---------
beautifulsoup4     4.11.1
brotli             1.2.0
certifi            2026.4.22
cffi               2.0.0
chardet            3.0.4
charset-normalizer 3.4.7
click              7.1.2
cryptography       36.0.1
flask              1.1.4
flask-basicauth    0.2.0
flask-sockets      0.2.1
gevent             22.8.0
gevent-websocket   0.10.1
greenlet           1.1.3
hpack              4.0.0
idna               3.14
itsdangerous       1.1.0
jinja2             2.11.3
lxml               4.9.1
markupsafe         2.0.1
pip-system-certs   4.0
pyasn1             0.6.3
pycparser          2.23
pyhttpx            2.10.9
pyopenssl          21.0.0
pysocks            1.7.1
requests           2.31.0
rsa                4.8
setuptools         81.0.0
six                1.17.0
soupsieve          2.8.3
termcolor          1.1.0
urllib3            2.6.3
werkzeug           1.0.1
wrapt              2.1.2
zope-event         6.0
zope-interface     8.0.1
```
以及似乎有个重复issue： #300

**Comment by ilolipopi** [comment]
应该是cookie的问题，我把cookie删了反而可以正常解析360p了。#255 里面[wibe01204](https://github.com/miyouzi/aniGamerPlus/issues/255#issuecomment-1732544313)提到：
> 我直接用f12進去後慢慢找，然後找到的那串可以用 用指令找的反而不行

还可参见#110
