### ISSUE TITLE
開啟後報錯，然後他就自動關掉了

### ISSUE THREAD

**Issue by ava6735** [miyouzi/aniGamerPlus#292]
Traceback (most recent call last):
  File "aniGamerPlus.py", line 1014, in <module>
  File "Config.py", line 674, in test_cookie
  File "Config.py", line 703, in read_cookie
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[12504] Failed to execute script 'aniGamerPlus' due to unhandled exception!

**Comment by miyouzi** [comment]
看起來cookie.txt文件有點問題，刪除cookie.txt看看是否能啟動，獲取cookie請參照readme

**Comment by ava6735** [comment]
可以用了
謝謝
