### ISSUE TITLE
无法下载了

### ISSUE THREAD

**Issue by tianmeiyouwo-123** [miyouzi/aniGamerPlus#55]
2020-08-05 14:24:38 check_no_ad: Ads not away?: sn=16490 2020-08-05 14:24:40 下載異常: sn=16490  發生未知錯誤: 'src' 2020-08-05 14:24:40 任务失敗: sn=16490  title="籃球少年王 [42]" 從任務列隊中移除 , 等待下次更新重試.

**Comment by miyouzi** [comment]
似乎在今天晚上，網站的强制廣告等待時間增加了，請等待修復

**Comment by miyouzi** [comment]
[v20.0](https://github.com/miyouzi/aniGamerPlus/releases/tag/v20.0) 已發佈，同時新增了Web控制臺，歡迎使用

**Comment by andy7557** [comment]
感謝更新，不過使用 EXE 執行檔時發生以下錯誤
請問是我在操作上有哪裡不正確嗎?

2020-08-08 14:05:29 下載異常: sn=16486  發生未知錯誤: 'ads_time'
2020-08-08 14:05:29 下載異常: sn=16486  異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 220, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "Anime.py", line 707, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "Anime.py", line 373, in __get_m3u8_dict
    ad_time = self._settings['ads_time']
KeyError: 'ads_time'

**Comment by miyouzi** [comment]
抱歉，升級配置時忘記添加```ads_time```了，你手動向 ```config.json``` 添加一下  ```"ads_time": 25,```，可以參考 ```config-sample.json```

我稍後更新代碼

**Comment by andy7557** [comment]
> 抱歉，升級配置時忘記添加`ads_time`了，你手動向 `config.json` 添加一下 `"ads_time": 25,`，可以參考 `config-sample.json`
> 
> 我稍後更新代碼

感謝回覆，修改後已可正常執行

**Comment by miyouzi** [comment]
代碼已修改完成，windows軟件包已替換，可以重新下載修正的版本（修正版配置文件版本為14.1）。
