### ISSUE TITLE
無法下載

### ISSUE THREAD

**Issue by mctea01** [miyouzi/aniGamerPlus#56]
## 問題描述
2020-08-06 13:52:18 check_no_ad: Ads not away?: sn=16588                                                                                                                                        2020-08-06 13:52:18 下載異常: sn=16588  發生未知錯誤: 'src'                                                                                                                                     2020-08-06 13:52:18 下載異常: sn=16588  異常詳情:                                                                                                                                               Traceback (most recent call last):                                                                                                                                                                File "aniGamerPlus.py", line 226, in worker                                                                                                                                                       realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])                                                                                                       File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download                                                                                                                                self.__get_m3u8_dict()  # 获取 m3u8 列表                                                                                                                                                      File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict                                                                                                                         parse_playlist()                                                                                                                                                                              File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist                                                                                                                          req = self._playlist['src']                                                                                                                                                                 KeyError: 'src'
## config.json 配置
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 12.0,
    "database_version": 2.0
}

## sn_list.txt 配置
90 all
16344 all
15298 all
16522 all
11392 all
12085 all

2020-08-06 13:22:36 檢查更新 檢查更新成功
2020-08-06 13:22:36 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v19.4 
2020-08-06 13:22:36 工作目錄: D:\Tools\anivd\aniGamerPlus 
2020-08-06 13:22:36 開始更新 
2020-08-06 13:22:36 讀取cookie 發現cookie檔案
2020-08-06 13:22:36 讀取cookie 已讀取cookie
2020-08-06 13:22:36 更新資訊: sn=90	正在檢查《冰菓》
2020-08-06 13:22:37 更新資訊: sn=16344	正在檢查《Re：從零開始的異世界生活 第二季》
2020-08-06 13:22:38 更新資訊: sn=15298	正在檢查《輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季》
2020-08-06 13:22:39 更新資訊: sn=16522	正在檢查《魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～》
2020-08-06 13:22:39 更新資訊: sn=11392	正在檢查《笨拙之極的上野》
2020-08-06 13:22:39 更新資訊: sn=12085	正在檢查《為什麼老師會在這裡！？》
2020-08-06 13:22:39 加入任务列隊: sn=16588	
2020-08-06 13:22:39 加入任务列隊: sn=11440	
2020-08-06 13:22:39 加入任务列隊: sn=11489	
2020-08-06 13:22:39 加入任务列隊: sn=11490	
2020-08-06 13:22:39 加入任务列隊: sn=11714	
2020-08-06 13:22:39 加入任务列隊: sn=11715	
2020-08-06 13:22:39 加入任务列隊: sn=11716	
2020-08-06 13:22:39 加入任务列隊: sn=11861	
2020-08-06 13:22:39 加入任务列隊: sn=11862	
2020-08-06 13:22:39 加入任务列隊: sn=11863	
2020-08-06 13:22:39 加入任务列隊: sn=12085	
2020-08-06 13:22:39 加入任务列隊: sn=12111	
2020-08-06 13:22:39 加入任务列隊: sn=12159	
2020-08-06 13:22:39 加入任务列隊: sn=12160	
2020-08-06 13:22:39 加入任务列隊: sn=12176	
2020-08-06 13:22:39 加入任务列隊: sn=12177	
2020-08-06 13:22:39 加入任务列隊: sn=12178	
2020-08-06 13:22:39 加入任务列隊: sn=12283	
2020-08-06 13:22:39 加入任务列隊: sn=12284	
2020-08-06 13:22:39 加入任务列隊: sn=12381	
2020-08-06 13:22:39 加入任务列隊: sn=12382	
2020-08-06 13:22:39 加入任务列隊: sn=12383	
2020-08-06 13:22:39 加入任务列隊: sn=16653	
2020-08-06 13:22:39 更新資訊 本次更新添加了 23 個新任務, 目前列隊中共有 23 個任務
2020-08-06 13:22:39 更新终了 
2020-08-06 13:22:40 正在等待: sn=16588	《Re：從零開始的異世界生活 第二季 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:23:02 check_no_ad: Ads not away?: sn=16588	
2020-08-06 13:23:02 下載異常: sn=16588	發生未知錯誤: 'src'
2020-08-06 13:23:02 下載異常: sn=16588	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:23:02 任务失敗: sn=16588	title="Re：從零開始的異世界生活 第二季 [5]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:23:04 正在等待: sn=11440	《笨拙之極的上野 [4]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:23:26 check_no_ad: Ads not away?: sn=11440	
2020-08-06 13:23:26 下載異常: sn=11440	發生未知錯誤: 'src'
2020-08-06 13:23:26 下載異常: sn=11440	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:23:26 任务失敗: sn=11440	title="笨拙之極的上野 [4]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:23:27 正在等待: sn=11489	《笨拙之極的上野 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:23:48 check_no_ad: Ads not away?: sn=11489	
2020-08-06 13:23:48 下載異常: sn=11489	發生未知錯誤: 'src'
2020-08-06 13:23:48 下載異常: sn=11489	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:23:48 任务失敗: sn=11489	title="笨拙之極的上野 [5]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:23:49 正在等待: sn=11490	《笨拙之極的上野 [6]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:24:09 check_no_ad: Ads not away?: sn=11490	
2020-08-06 13:24:10 下載異常: sn=11490	發生未知錯誤: 'src'
2020-08-06 13:24:10 下載異常: sn=11490	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:24:10 任务失敗: sn=11490	title="笨拙之極的上野 [6]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:24:12 正在等待: sn=11714	《笨拙之極的上野 [7]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:24:32 check_no_ad: Ads not away?: sn=11714	
2020-08-06 13:24:32 下載異常: sn=11714	發生未知錯誤: 'src'
2020-08-06 13:24:32 下載異常: sn=11714	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:24:32 任务失敗: sn=11714	title="笨拙之極的上野 [7]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:24:33 正在等待: sn=11715	《笨拙之極的上野 [8]》 由於不是VIP賬戶, 正在等待20s廣告時間

2020-08-06 13:24:37 你終止了程序! 

2020-08-06 13:26:52 檢查更新 檢查更新成功
2020-08-06 13:26:52 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v19.4 
2020-08-06 13:26:52 工作目錄: D:\Tools\anivd\aniGamerPlus 
2020-08-06 13:26:52 開始更新 
2020-08-06 13:26:52 讀取cookie 發現cookie檔案
2020-08-06 13:26:52 讀取cookie 已讀取cookie
2020-08-06 13:26:52 更新資訊: sn=90	正在檢查《冰菓》
2020-08-06 13:26:53 更新資訊: sn=16344	正在檢查《Re：從零開始的異世界生活 第二季》
2020-08-06 13:26:53 更新資訊: sn=15298	正在檢查《輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季》
2020-08-06 13:26:54 更新資訊: sn=16522	正在檢查《魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～》
2020-08-06 13:26:54 更新資訊: sn=11392	正在檢查《笨拙之極的上野》
2020-08-06 13:26:54 更新資訊: sn=12085	正在檢查《為什麼老師會在這裡！？》
2020-08-06 13:26:54 加入任务列隊: sn=16588	
2020-08-06 13:26:54 加入任务列隊: sn=11440	
2020-08-06 13:26:54 加入任务列隊: sn=11489	
2020-08-06 13:26:54 加入任务列隊: sn=11490	
2020-08-06 13:26:54 加入任务列隊: sn=11714	
2020-08-06 13:26:54 加入任务列隊: sn=11715	
2020-08-06 13:26:54 加入任务列隊: sn=11716	
2020-08-06 13:26:54 加入任务列隊: sn=11861	
2020-08-06 13:26:54 加入任务列隊: sn=11862	
2020-08-06 13:26:54 加入任务列隊: sn=11863	
2020-08-06 13:26:54 加入任务列隊: sn=12085	
2020-08-06 13:26:54 加入任务列隊: sn=12111	
2020-08-06 13:26:54 加入任务列隊: sn=12159	
2020-08-06 13:26:54 加入任务列隊: sn=12160	
2020-08-06 13:26:55 加入任务列隊: sn=12176	
2020-08-06 13:26:55 加入任务列隊: sn=12177	
2020-08-06 13:26:55 加入任务列隊: sn=12178	
2020-08-06 13:26:55 加入任务列隊: sn=12283	
2020-08-06 13:26:55 加入任务列隊: sn=12284	
2020-08-06 13:26:55 加入任务列隊: sn=12381	
2020-08-06 13:26:55 加入任务列隊: sn=12382	
2020-08-06 13:26:55 加入任务列隊: sn=12383	
2020-08-06 13:26:55 加入任务列隊: sn=16653	
2020-08-06 13:26:55 更新資訊 本次更新添加了 23 個新任務, 目前列隊中共有 23 個任務
2020-08-06 13:26:55 更新终了 
2020-08-06 13:26:55 正在等待: sn=16588	《Re：從零開始的異世界生活 第二季 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:27:15 check_no_ad: Ads not away?: sn=16588	
2020-08-06 13:27:16 下載異常: sn=16588	發生未知錯誤: 'src'
2020-08-06 13:27:16 下載異常: sn=16588	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:27:16 任务失敗: sn=16588	title="Re：從零開始的異世界生活 第二季 [5]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:27:17 正在等待: sn=11440	《笨拙之極的上野 [4]》 由於不是VIP賬戶, 正在等待20s廣告時間

2020-08-06 13:27:18 你終止了程序! 

2020-08-06 13:39:56 檢查更新 檢查更新成功
2020-08-06 13:39:56 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v19.4 
2020-08-06 13:39:56 工作目錄: D:\Tools\anivd\aniGamerPlus 
2020-08-06 13:39:56 開始更新 
2020-08-06 13:39:56 讀取cookie 發現cookie檔案
2020-08-06 13:39:56 讀取cookie 已讀取cookie
2020-08-06 13:39:58 更新資訊: sn=90	正在檢查《冰菓》
2020-08-06 13:39:59 更新資訊: sn=16344	正在檢查《Re：從零開始的異世界生活 第二季》
2020-08-06 13:40:00 更新資訊: sn=15298	正在檢查《輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季》
2020-08-06 13:40:01 更新資訊: sn=16522	正在檢查《魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～》
2020-08-06 13:40:02 更新資訊: sn=11392	正在檢查《笨拙之極的上野》
2020-08-06 13:40:03 更新資訊: sn=12085	正在檢查《為什麼老師會在這裡！？》
2020-08-06 13:40:03 加入任务列隊: sn=16588	
2020-08-06 13:40:03 加入任务列隊: sn=11440	
2020-08-06 13:40:03 加入任务列隊: sn=11489	
2020-08-06 13:40:03 加入任务列隊: sn=11490	
2020-08-06 13:40:03 加入任务列隊: sn=11714	
2020-08-06 13:40:03 加入任务列隊: sn=11715	
2020-08-06 13:40:03 加入任务列隊: sn=11716	
2020-08-06 13:40:03 加入任务列隊: sn=11861	
2020-08-06 13:40:03 加入任务列隊: sn=11862	
2020-08-06 13:40:03 加入任务列隊: sn=11863	
2020-08-06 13:40:03 加入任务列隊: sn=12085	
2020-08-06 13:40:03 加入任务列隊: sn=12111	
2020-08-06 13:40:03 加入任务列隊: sn=12159	
2020-08-06 13:40:03 加入任务列隊: sn=12160	
2020-08-06 13:40:03 加入任务列隊: sn=12176	
2020-08-06 13:40:03 加入任务列隊: sn=12177	
2020-08-06 13:40:03 加入任务列隊: sn=12178	
2020-08-06 13:40:03 加入任务列隊: sn=12283	
2020-08-06 13:40:03 加入任务列隊: sn=12284	
2020-08-06 13:40:03 加入任务列隊: sn=12381	
2020-08-06 13:40:03 加入任务列隊: sn=12382	
2020-08-06 13:40:03 加入任务列隊: sn=12383	
2020-08-06 13:40:03 加入任务列隊: sn=16653	
2020-08-06 13:40:03 更新資訊 本次更新添加了 23 個新任務, 目前列隊中共有 23 個任務
2020-08-06 13:40:03 更新终了 
2020-08-06 13:40:06 正在等待: sn=16588	《Re：從零開始的異世界生活 第二季 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:40:29 check_no_ad: Ads not away?: sn=16588	
2020-08-06 13:40:29 下載異常: sn=16588	發生未知錯誤: 'src'
2020-08-06 13:40:29 下載異常: sn=16588	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:40:29 任务失敗: sn=16588	title="Re：從零開始的異世界生活 第二季 [5]" 從任務列隊中移除, 等待下次更新重試.

2020-08-06 13:40:30 你終止了程序! 

2020-08-06 13:43:39 檢查更新 檢查更新成功
2020-08-06 13:43:39 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v19.4 
2020-08-06 13:43:39 工作目錄: D:\Tools\anivd\aniGamerPlus 
2020-08-06 13:43:39 開始更新 
2020-08-06 13:43:39 讀取cookie 發現cookie檔案
2020-08-06 13:43:39 讀取cookie 已讀取cookie
2020-08-06 13:43:39 更新資訊: sn=90	正在檢查《冰菓》
2020-08-06 13:43:39 更新資訊: sn=16344	正在檢查《Re：從零開始的異世界生活 第二季》
2020-08-06 13:43:40 更新資訊: sn=15298	正在檢查《輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季》
2020-08-06 13:43:40 更新資訊: sn=16522	正在檢查《魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～》
2020-08-06 13:43:40 更新資訊: sn=11392	正在檢查《笨拙之極的上野》
2020-08-06 13:43:41 更新資訊: sn=12085	正在檢查《為什麼老師會在這裡！？》
2020-08-06 13:43:41 加入任务列隊: sn=16588	
2020-08-06 13:43:41 加入任务列隊: sn=11440	
2020-08-06 13:43:41 加入任务列隊: sn=11489	
2020-08-06 13:43:41 加入任务列隊: sn=11490	
2020-08-06 13:43:41 加入任务列隊: sn=11714	
2020-08-06 13:43:41 加入任务列隊: sn=11715	
2020-08-06 13:43:41 加入任务列隊: sn=11716	
2020-08-06 13:43:41 加入任务列隊: sn=11861	
2020-08-06 13:43:41 加入任务列隊: sn=11862	
2020-08-06 13:43:41 加入任务列隊: sn=11863	
2020-08-06 13:43:41 加入任务列隊: sn=12085	
2020-08-06 13:43:41 加入任务列隊: sn=12111	
2020-08-06 13:43:41 加入任务列隊: sn=12159	
2020-08-06 13:43:41 加入任务列隊: sn=12160	
2020-08-06 13:43:41 加入任务列隊: sn=12176	
2020-08-06 13:43:41 加入任务列隊: sn=12177	
2020-08-06 13:43:41 加入任务列隊: sn=12178	
2020-08-06 13:43:41 加入任务列隊: sn=12283	
2020-08-06 13:43:41 加入任务列隊: sn=12284	
2020-08-06 13:43:41 加入任务列隊: sn=12381	
2020-08-06 13:43:41 加入任务列隊: sn=12382	
2020-08-06 13:43:41 加入任务列隊: sn=12383	
2020-08-06 13:43:41 加入任务列隊: sn=16653	
2020-08-06 13:43:41 更新資訊 本次更新添加了 23 個新任務, 目前列隊中共有 23 個任務
2020-08-06 13:43:41 更新终了 
2020-08-06 13:43:42 正在等待: sn=16588	《Re：從零開始的異世界生活 第二季 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:44:02 check_no_ad: Ads not away?: sn=16588	
2020-08-06 13:44:02 下載異常: sn=16588	發生未知錯誤: 'src'
2020-08-06 13:44:02 下載異常: sn=16588	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:44:02 任务失敗: sn=16588	title="Re：從零開始的異世界生活 第二季 [5]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:44:03 正在等待: sn=11440	《笨拙之極的上野 [4]》 由於不是VIP賬戶, 正在等待20s廣告時間

2020-08-06 13:44:03 你終止了程序! 

2020-08-06 13:51:54 檢查更新 檢查更新成功
2020-08-06 13:51:54 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v19.4 
2020-08-06 13:51:54 工作目錄: D:\Tools\anivd\aniGamerPlus 
2020-08-06 13:51:54 開始更新 
2020-08-06 13:51:54 讀取cookie 發現cookie檔案
2020-08-06 13:51:54 讀取cookie 已讀取cookie
2020-08-06 13:51:54 更新資訊: sn=90	正在檢查《冰菓》
2020-08-06 13:51:55 更新資訊: sn=16344	正在檢查《Re：從零開始的異世界生活 第二季》
2020-08-06 13:51:55 更新資訊: sn=15298	正在檢查《輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季》
2020-08-06 13:51:55 更新資訊: sn=16522	正在檢查《魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～》
2020-08-06 13:51:56 更新資訊: sn=11392	正在檢查《笨拙之極的上野》
2020-08-06 13:51:56 更新資訊: sn=12085	正在檢查《為什麼老師會在這裡！？》
2020-08-06 13:51:56 加入任务列隊: sn=16588	
2020-08-06 13:51:56 加入任务列隊: sn=11440	
2020-08-06 13:51:56 加入任务列隊: sn=11489	
2020-08-06 13:51:56 加入任务列隊: sn=11490	
2020-08-06 13:51:56 加入任务列隊: sn=11714	
2020-08-06 13:51:56 加入任务列隊: sn=11715	
2020-08-06 13:51:56 加入任务列隊: sn=11716	
2020-08-06 13:51:56 加入任务列隊: sn=11861	
2020-08-06 13:51:56 加入任务列隊: sn=11862	
2020-08-06 13:51:56 加入任务列隊: sn=11863	
2020-08-06 13:51:56 加入任务列隊: sn=12085	
2020-08-06 13:51:56 加入任务列隊: sn=12111	
2020-08-06 13:51:56 加入任务列隊: sn=12159	
2020-08-06 13:51:56 加入任务列隊: sn=12160	
2020-08-06 13:51:57 加入任务列隊: sn=12176	
2020-08-06 13:51:57 加入任务列隊: sn=12177	
2020-08-06 13:51:57 加入任务列隊: sn=12178	
2020-08-06 13:51:57 加入任务列隊: sn=12283	
2020-08-06 13:51:57 加入任务列隊: sn=12284	
2020-08-06 13:51:57 加入任务列隊: sn=12381	
2020-08-06 13:51:57 加入任务列隊: sn=12382	
2020-08-06 13:51:57 加入任务列隊: sn=12383	
2020-08-06 13:51:57 加入任务列隊: sn=16653	
2020-08-06 13:51:57 更新資訊 本次更新添加了 23 個新任務, 目前列隊中共有 23 個任務
2020-08-06 13:51:57 更新终了 
2020-08-06 13:51:57 正在等待: sn=16588	《Re：從零開始的異世界生活 第二季 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:52:18 check_no_ad: Ads not away?: sn=16588	
2020-08-06 13:52:18 下載異常: sn=16588	發生未知錯誤: 'src'
2020-08-06 13:52:18 下載異常: sn=16588	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:52:18 任务失敗: sn=16588	title="Re：從零開始的異世界生活 第二季 [5]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:52:19 正在等待: sn=11440	《笨拙之極的上野 [4]》 由於不是VIP賬戶, 正在等待20s廣告時間
2020-08-06 13:52:39 check_no_ad: Ads not away?: sn=11440	
2020-08-06 13:52:40 下載異常: sn=11440	發生未知錯誤: 'src'
2020-08-06 13:52:40 下載異常: sn=11440	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 226, in worker
    realtime_show_file_size=realtime_show_file_size, classify=settings['classify_bangumi'])
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 693, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 372, in __get_m3u8_dict
    parse_playlist()
  File "D:\Tools\anivd\aniGamerPlus\Anime.py", line 331, in parse_playlist
    req = self._playlist['src']
KeyError: 'src'

2020-08-06 13:52:40 任务失敗: sn=11440	title="笨拙之極的上野 [4]" 從任務列隊中移除, 等待下次更新重試.
2020-08-06 13:52:41 正在等待: sn=11489	《笨拙之極的上野 [5]》 由於不是VIP賬戶, 正在等待20s廣告時間

2020-08-06 13:52:41 你終止了程序!

**Comment by miyouzi** [comment]
與 #55 問題相同
