### ISSUE TITLE
'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by hungte** [miyouzi/aniGamerPlus#71]
## 問題描述
最近重新安裝系統，內建的是 python 3.9, 執行後會出現錯誤 'Thread' object has no attribute 'isAlive'。
查了一下 Python3 應該使用 is_alive(), 雖然不知為何之前都沒出現錯誤。

## 錯誤截圖
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hungte/Downloads/media/aniGamerPlus/Dashboard/Server.py", line 126, in run_cui
    cui(data['sn'], resolution, mode, thread_limit, [], classify=data['classify'], realtime_show=False)
  File "/Users/hungte/Downloads/media/aniGamerPlus/aniGamerPlus.py", line 408, in __cui
    anime.download(cui_resolution, cui_save_dir, realtime_show_file_size=realtime_show_file_size, classify=classify)
  File "/Users/hungte/Downloads/media/aniGamerPlus/Anime.py", line 791, in download
    self.__segment_download_mode(resolution)
  File "/Users/hungte/Downloads/media/aniGamerPlus/Anime.py", line 552, in __segment_download_mode
    if task.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```
## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 2,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537
.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 14.2,
    "database_version": 2.0,
    "use_mobile_api": false
}
```

**Comment by kirbyloco** [comment]
在Python 3.8之前(含3.8)用isAlive都沒問題
只是會寫該方法已淘汰不推薦使用
但在Python 3.9就正式淘汰了
