### ISSUE TITLE
chrome更新後功能失效

### ISSUE THREAD

**Issue by HolyTing** [miyouzi/aniGamerPlus#87]
您好，最近chrome更新到87.0.4280.88 後，aniGamerPlus就失效了。

**Comment by miyouzi** [comment]
能具體一點嗎？失效是什麼失效？Web控制台有什麼問題還是下載報錯？報什麼錯？

**Comment by HolyTing** [comment]
抱歉沒說清楚，是下載報錯
我用Web控制台添加手動任務下載影片
全部預設選項
開始下載後出現下面那串
最後報 IndexError: list index out of range


2020-12-10 09:04:53 Dashboard 通過 Web 控制臺下達了手動任務
當前下載模式: 僅下載本集

2020-12-10 09:04:53 開始下載: sn=19674  《熊熊勇闖異世界 [10]》 識別到VIP賬戶, 立即下載
2020-12-10 09:04:54 正在下載: sn=19674  【動畫瘋】熊熊勇闖異世界[10][1080P].mp4 title=熊熊勇闖異世界 [10]
2020-12-10 09:05:34 下載狀態: sn=19674  【動畫瘋】熊熊勇闖異世界[10][1080P].mp4 下載完成, 正在解密合并……
2020-12-10 09:05:34 下載異常: sn=19674  發生未知異常: [WinError 2] 系統找不到指定的檔案。: 'D:\\aniGamerPlus_v22.0_windows_64bit\\temp\\【動畫瘋】熊熊勇闖異世界[10][1080P].MERGING.mp4'
2020-12-10 09:05:34 任務失敗: sn=19674  title=熊熊勇闖異世界 [10] 10s后自動重啓,最多重試三次
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "Dashboard\Server.py", line 149, in run_cui
  File "aniGamerPlus.py", line 415, in __cui
  File "aniGamerPlus.py", line 363, in __download_only
  File "Anime.py", line 84, in renew
  File "Anime.py", line 189, in __get_episode_list
IndexError: list index out of range

**Comment by miyouzi** [comment]
你可能遇到和 #80 一樣的問題，你 ffmpeg 版本多少？嘗試升級一下 ffmpeg ？

**Comment by HolyTing** [comment]
謝謝，換了最新版的ffmpeg 之後就可以了
